name: Deploy to EKS via Helm

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      EKS_CLUSTER_NAME:
        required: true
      ECR_REPOSITORY:
        required: true

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Helm artifact
        uses: actions/download-artifact@v4
        with:
          name: helm-chart
          path: ./artifacts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy with Helm
        run: |
          CHART=$(ls ./artifacts/*.tgz)
          helm upgrade --install my-app "$CHART" \
            --namespace default --create-namespace \
            --set image.repository=${{ secrets.ECR_REPOSITORY }} \
            --set image.tag=${{ github.sha }}
