name: CICD - Build and Deploy Java App

on:
  push:
    paths:
      - 'JavaApp/**'
      - '.github/workflows/main-pipeline.yml'
  
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      image-name: java-app
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-app.yml
    secrets: inherit