name: CICD - Build and Deploy Java App

on:
  push:
    paths:
      - 'JavaApp/**'
      - '.github/workflows/main-pipeline.yml'
  
  workflow_dispatch:

## This is for OIDC based authentication of GitHub with AWS
permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/actions/build-image.yml
    with:
      image-name: java-app
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/actions/deploy-app.yml
    secrets: inherit